In [1]:
matris1=[[7,6,3],[4,4,2]]

In [3]:
matris2=[[-2,7,2],[1,1,9]]

In [4]:
import numpy as np

In [5]:
array1=np.zeros((3,2))

In [7]:
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
array2=np.ones((3,3))

In [9]:
print(array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
random_number=np.random.rand(4)

In [24]:
print(random_number)

[0.37895049 0.93115777 0.71974867 0.54626761]


In [25]:
variable1=24
variable2=33
if(variable1>=variable2):
    print("variable1 is greater than variable2")
elif(variable1==variable2):
    print("the numbers are equal")
else:
    print("variable2 is greater than variable1")
    

variable2 is greater than variable1


In [29]:
list1=[12,13,14,15,16]
for i in list1:
    print(i)

12
13
14
15
16


In [28]:
list2=[2,9,17,3,19]
list3=[13,4,4,5,20]
def sum_arrays(array1,array2):
    sum_of_arrays=0
    for i in range(len(array1)):
        sum_of_arrays+=array1[i]+array2[i]
    return sum_of_arrays
print(sum_arrays(list2,list3))

96


In [30]:
input1=input("please enter something")
def print_new(something):
    print(something)
print_new(input1)

please enter somethingselam
selam
